// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxetXQfYFNvsWTGEhdPlaN4QM2D20x40',
    appId: '1:956903556592:web:b0612d5065019069f80935',
    messagingSenderId: '956903556592',
    projectId: 'ecommerce-8ccd0',
    authDomain: 'ecommerce-8ccd0.firebaseapp.com',
    databaseURL: 'https://ecommerce-8ccd0-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-8ccd0.appspot.com',
    measurementId: 'G-HWRJBBFVEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOMnOQ4uSDNo-Ga6GBkEm1gFUhbAdYlpI',
    appId: '1:956903556592:android:a292f8f88a51d2fdf80935',
    messagingSenderId: '956903556592',
    projectId: 'ecommerce-8ccd0',
    databaseURL: 'https://ecommerce-8ccd0-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-8ccd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV7Lmkd2nJ66WpHc_sA4X1ldUIL2P2gjs',
    appId: '1:956903556592:ios:6bdb87f30b016c03f80935',
    messagingSenderId: '956903556592',
    projectId: 'ecommerce-8ccd0',
    databaseURL: 'https://ecommerce-8ccd0-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-8ccd0.appspot.com',
    iosBundleId: 'com.example.ecommercefarmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV7Lmkd2nJ66WpHc_sA4X1ldUIL2P2gjs',
    appId: '1:956903556592:ios:68bebca37c87112df80935',
    messagingSenderId: '956903556592',
    projectId: 'ecommerce-8ccd0',
    databaseURL: 'https://ecommerce-8ccd0-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-8ccd0.appspot.com',
    iosBundleId: 'com.example.ecommercefarmer.RunnerTests',
  );
}
